### PR TITLE
Fix for Emacs 26.2 tramp

### PR DESCRIPTION
**Pull request by apauzies**
Reverting this: https://github.com/randymorris/tramp-term.el/issues/4

### CODE REVIEW

**Comment by phil-s** [comment]
As I understand it, #4 was necessary for 26.1 and no other version (i.e. a bug was introduced in 26.1 and fixed in 26.2).

If so, then rather than reverting #4 (which will then break the library for all users of 26.1), it should actually be modified so that it only applies if the Emacs version is 26.1.

**Comment by apauzies** [comment]
That's what I understood to: 26.1 is the one with the problem but maybe others?

I've updated my change

**Comment by randymorris** [comment]
Hi everyone.  Sorry for my silence on this.  I don't have access to an environment where I can test against newer versions of emacs anymore, but since this patch appears to specifically allow 26.1 to continue working as expected.  I think that in order for Melpa to notice the change the version number in the header comments will need to be bumped.  Any chance you could go ahead and do that as a part of this change to keep it all together?


Unfortunately I don't have the time to manage this project like I'd like (even though it has hardly ever required attention) so if either of you wants to take over just let me know.

**Comment by apauzies** [comment]
Done

**Comment by randymorris** [comment]
Thanks @apauzies.  I appreciate the help.

**Pull request merged**
